<template>
	<form
		class="food"
		v-on:submit.prevent="submit"
	>
	    <ul
	    	class="
	    		grid
				grid--quarters
				grid--gutters
				grid--vertGutters
				ut-clearListOnly
	    	"
	    >
	        <li
	        	v-for="(food, key) in foods"
        	>
	        	<article
					class="card"
				>
					<div
						class="
							card__body
						"
					>
			            <h3>
			            	<label
			            		v-text="key"
			            	/>
			            </h3>
			            <input 
			            	type="number"
			            	v-model.number="food.weight"
			            />
			        </div>
			    </article>
	        </li>
	    </ul>
	    <button
	    	class="button"
			v-on:click.prevent="random"
    	>
    		Random meal plan
    	</button>
	    <button
	    	type="submit"
	    	class="button"
    	>
    		Save
    	</button>
	</form>
</template>

<script src="./VFood.js"/>